<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\MasterBarang;
use App\Models\MasterSatuan;
use App\Models\BarangSatuanKonversi;
use App\Models\StockGudang;
use App\Models\Ubs;

class MasterBarangExcelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Array Data dari Excel (BRG-0001 s/d BRG-0236)
        $dataExcel = [
            // BRG-0001 s/d BRG-0100
            [
                'kode_barang'              => 'BRG-0001',
                'nama_barang'              => 'Acian Bata Ringan',
                'satuan_terkecil'          => 'sak',
                'satuan'                   => 'sak',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'sak',
            ],
            [
                'kode_barang'              => 'BRG-0002',
                'nama_barang'              => 'Afur pvc',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0003',
                'nama_barang'              => 'Amplas',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
            ],
            [
                'kode_barang'              => 'BRG-0004',
                'nama_barang'              => 'Asano PU foam',
                'satuan_terkecil'          => 'tabung',
                'satuan'                   => 'tabung',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'tabung',
            ],
            [
                'kode_barang'              => 'BRG-0005',
                'nama_barang'              => 'Bak cuci piring',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0006',
                'nama_barang'              => 'Bambu 4mtr',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0007',
                'nama_barang'              => 'Bambu lonjoran',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0008',
                'nama_barang'              => 'Baut canal',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0009',
                'nama_barang'              => 'Baut reng',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0010',
                'nama_barang'              => 'Baut spandek',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0011',
                'nama_barang'              => 'Begel 10 x 10',
                'satuan_terkecil'          => 'KG',
                'satuan'                   => 'KG',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'KG',
            ],
            [
                'kode_barang'              => 'BRG-0012',
                'nama_barang'              => 'Begel 10 x 15',
                'satuan_terkecil'          => 'KG',
                'satuan'                   => 'KG',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'KG',
            ],
            [
                'kode_barang'              => 'BRG-0013',
                'nama_barang'              => 'Begel 12 x 25',
                'satuan_terkecil'          => 'KG',
                'satuan'                   => 'KG',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'KG',
            ],
            [
                'kode_barang'              => 'BRG-0014',
                'nama_barang'              => 'Begel 25 x 25',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0015',
                'nama_barang'              => 'Begel 7 x 12',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0016',
                'nama_barang'              => 'Benang bol',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0017',
                'nama_barang'              => 'Bendrat',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0018',
                'nama_barang'              => 'Besi 10 SNI/HIJ',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0019',
                'nama_barang'              => 'Besi 6mm',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0020',
                'nama_barang'              => 'Besi 8 SNI/HIJ',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0021',
                'nama_barang'              => 'Besi 12 HIJ',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0022',
                'nama_barang'              => 'Besi holo 2x2',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0023',
                'nama_barang'              => 'Besi holo 2x4',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0024',
                'nama_barang'              => 'Besi holo 1.5x1.5',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0025',
                'nama_barang'              => 'Besi holo 4x1',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0026',
                'nama_barang'              => 'Besi holo 4x6',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0027',
                'nama_barang'              => 'Besi holo 4x8',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0028',
                'nama_barang'              => 'Cairan Aspal Flas watterofing',
                'satuan_terkecil'          => 'jurigen',
                'satuan'                   => 'jurigen',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'jurigen',
            ],
            [
                'kode_barang'              => 'BRG-0029',
                'nama_barang'              => 'Canal C75x0',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0030',
                'nama_barang'              => 'Cat AVITEX 893',
                'satuan_terkecil'          => 'pail',
                'satuan'                   => 'pail',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pail',
            ],
            [
                'kode_barang'              => 'BRG-0031',
                'nama_barang'              => 'Cat elastek sadle brown 5 Kg',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0032',
                'nama_barang'              => 'Cat Interior Inpro',
                'satuan_terkecil'          => 'pail',
                'satuan'                   => 'pail',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pail',
            ],
            [
                'kode_barang'              => 'BRG-0033',
                'nama_barang'              => 'Cat no drop 032',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0034',
                'nama_barang'              => 'Cat no drop 002 ABU',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0035',
                'nama_barang'              => 'Cat no drop 009 PUTIH',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0036',
                'nama_barang'              => 'Cat yoko 77 Genteng Abu Abu',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0037',
                'nama_barang'              => 'Cat int jasmin sw',
                'satuan_terkecil'          => 'pail',
                'satuan'                   => 'pail',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pail',
            ],
            [
                'kode_barang'              => 'BRG-0038',
                'nama_barang'              => 'Cat yoko 77 List Hitam',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0039',
                'nama_barang'              => 'Cesmen 2 profil',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0040',
                'nama_barang'              => 'Corner bite',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0041',
                'nama_barang'              => 'Cornes',
                'satuan_terkecil'          => 'sak',
                'satuan'                   => 'sak',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'sak',
            ],
            [
                'kode_barang'              => 'BRG-0042',
                'nama_barang'              => 'Corong talang 2.5 dim & Pvc',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0043',
                'nama_barang'              => 'DCN 0111 Tutup Polos',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0044',
                'nama_barang'              => 'DCN Spigot',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0045',
                'nama_barang'              => 'DCN Tatapan',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0046',
                'nama_barang'              => 'Double nepel',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0047',
                'nama_barang'              => 'Dvp 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0048',
                'nama_barang'              => 'Dvp 1.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0049',
                'nama_barang'              => 'Dvp 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0050',
                'nama_barang'              => 'Dvp 3',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0051',
                'nama_barang'              => 'DOP 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0052',
                'nama_barang'              => 'Engsel 10',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0053',
                'nama_barang'              => 'Engsel 4 inci',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0054',
                'nama_barang'              => 'Engsel Desi Ebush 3/4',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0055',
                'nama_barang'              => 'Enjel',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0056',
                'nama_barang'              => 'Gergaji sanflex',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0057',
                'nama_barang'              => 'Grendel kuping',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0058',
                'nama_barang'              => 'HCL',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0059',
                'nama_barang'              => 'Holo Plafond',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0060',
                'nama_barang'              => 'Kalsiboard 1.2 x 2.4',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0061',
                'nama_barang'              => 'Kalsium',
                'satuan_terkecil'          => 'sak',
                'satuan'                   => 'sak',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'sak',
            ],
            [
                'kode_barang'              => 'BRG-0062',
                'nama_barang'              => 'Kapur Bubuk',
                'satuan_terkecil'          => 'sak',
                'satuan'                   => 'sak',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'sak',
            ],
            [
                'kode_barang'              => 'BRG-0063',
                'nama_barang'              => 'Karet C',
                'satuan_terkecil'          => 'rol',
                'satuan'                   => 'rol',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'rol',
            ],
            [
                'kode_barang'              => 'BRG-0064',
                'nama_barang'              => 'Karet O',
                'satuan_terkecil'          => 'rol',
                'satuan'                   => 'rol',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'rol',
            ],
            [
                'kode_barang'              => 'BRG-0065',
                'nama_barang'              => 'Kawat ayam (Ayakan alus)',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
            ],
            [
                'kode_barang'              => 'BRG-0066',
                'nama_barang'              => 'KDD 3/4 KE 1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0067',
                'nama_barang'              => 'Gypsum',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0068',
                'nama_barang'              => 'Keramik Glossy White 25x40',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0069',
                'nama_barang'              => 'Keramik Granit 60x60',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0070',
                'nama_barang'              => 'Keramik 50x50 Pelegrina Bianca',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0071',
                'nama_barang'              => 'Keramik 50x50 Latina Grey Rec A',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0072',
                'nama_barang'              => 'Keramik lantai 50x50 (marble grey)',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0073',
                'nama_barang'              => 'Keramik Lantai 50 x 50 Massimo',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0074',
                'nama_barang'              => 'Keramik 50x50 Luna Dark Grey',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0075',
                'nama_barang'              => 'Keramik lantai 40x40 (TIPE 30) Tarakan',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0076',
                'nama_barang'              => 'Keramik Motif Bata',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0077',
                'nama_barang'              => 'Kloset duduk',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0078',
                'nama_barang'              => 'Kloset jongkok',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0079',
                'nama_barang'              => 'Kne 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0080',
                'nama_barang'              => 'Kne 1 1/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0081',
                'nama_barang'              => 'Kne 1 1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0082',
                'nama_barang'              => 'Kne 1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0083',
                'nama_barang'              => 'Kne 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0084',
                'nama_barang'              => 'Kne 2.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0085',
                'nama_barang'              => 'Kne 3 dim',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0086',
                'nama_barang'              => 'Kne 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0087',
                'nama_barang'              => 'Kne 4 dim',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0088',
                'nama_barang'              => 'Kne 4 elbow',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0089',
                'nama_barang'              => 'Kne Drat 1/2 Kuningan',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0090',
                'nama_barang'              => 'Kran 1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0091',
                'nama_barang'              => 'Kran Shower',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0092',
                'nama_barang'              => 'Kuas 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0093',
                'nama_barang'              => 'Kuas 4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0094',
                'nama_barang'              => 'Kuas rol',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0095',
                'nama_barang'              => 'Kuas roll motif',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0096',
                'nama_barang'              => 'Kunci Slot',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0097',
                'nama_barang'              => 'Kunci bantol',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0098',
                'nama_barang'              => 'Kunci slot pagar',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0099',
                'nama_barang'              => 'DCN 0428 Kusen brown/white',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0100',
                'nama_barang'              => 'Knok Samping',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],

            // BRG-0101 s/d BRG-0236
            [
                'kode_barang'              => 'BRG-0101',
                'nama_barang'              => 'Lem Pipa odol',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0102',
                'nama_barang'              => 'Lem diplex kaleng',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0103',
                'nama_barang'              => 'Lem Plamir',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0104',
                'nama_barang'              => 'Lem silent',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0105',
                'nama_barang'              => 'Lem fox',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0106',
                'nama_barang'              => 'Lisplang polos',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0107',
                'nama_barang'              => 'List U',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0108',
                'nama_barang'              => 'Lampu Tempel',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0109',
                'nama_barang'              => 'Lampu led 7 watt',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0110',
                'nama_barang'              => 'Lampu led 9 watt',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0111',
                'nama_barang'              => 'Lampu led 12 watt',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0112',
                'nama_barang'              => 'Lampu 5 watt',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0113',
                'nama_barang'              => 'Lampu Sorot',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0114',
                'nama_barang'              => 'No drop 023',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0115',
                'nama_barang'              => 'No drop 010',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0116',
                'nama_barang'              => 'No Drop Hitam',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0117',
                'nama_barang'              => 'Mowilex 500',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0118',
                'nama_barang'              => 'OS 1.5-1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0119',
                'nama_barang'              => 'Os 2 ke 3/4 (Air Bersih)',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0120',
                'nama_barang'              => 'OS 3 ke 1.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0121',
                'nama_barang'              => 'OS 3 ke 2.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0122',
                'nama_barang'              => 'OS 3-1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0123',
                'nama_barang'              => 'OS 3/4 Ke 1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0124',
                'nama_barang'              => 'Oversok 1-3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0125',
                'nama_barang'              => 'OS 4-2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0126',
                'nama_barang'              => 'OS 4-3',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0127',
                'nama_barang'              => 'Oversok 2-3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0128',
                'nama_barang'              => 'Paku 1',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0129',
                'nama_barang'              => 'Paku 2 dim',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0130',
                'nama_barang'              => 'Paku 3 dim',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0131',
                'nama_barang'              => 'Paku Rivet Besar 540',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0132',
                'nama_barang'              => 'Paku Payung',
                'satuan_terkecil'          => 'kg',
                'satuan'                   => 'kg',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'kg',
            ],
            [
                'kode_barang'              => 'BRG-0133',
                'nama_barang'              => 'Perban tip',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0134',
                'nama_barang'              => 'Perekat Bata Ringan',
                'satuan_terkecil'          => 'sak',
                'satuan'                   => 'sak',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'sak',
            ],
            [
                'kode_barang'              => 'BRG-0135',
                'nama_barang'              => 'Pintu HPL Maroon',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0136',
                'nama_barang'              => 'Pintu Pvc',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0137',
                'nama_barang'              => 'Pipa 1.5 D',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0138',
                'nama_barang'              => 'Pipa 1 1/4',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0139',
                'nama_barang'              => 'Pipa 1 dim AW (power, triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0140',
                'nama_barang'              => 'Pipa 2 dim AW (power/triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0141',
                'nama_barang'              => 'Pipa 2 dim D ( power,triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0142',
                'nama_barang'              => 'Pipa 2.5 dim D (power,triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0143',
                'nama_barang'              => 'Pipa 2.5 dim C power',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0144',
                'nama_barang'              => 'Pipa 3 dim C (power,triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0145',
                'nama_barang'              => 'Pipa 3/4',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0146',
                'nama_barang'              => 'Pipa 4 AW (power,trilium)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0147',
                'nama_barang'              => 'Pipa 4 dim C (power, triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0148',
                'nama_barang'              => 'Pipa 4 dim D (power,triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0149',
                'nama_barang'              => 'Pipa 1 dim D (power,triliun)',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0150',
                'nama_barang'              => 'Pipa oval 2',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0151',
                'nama_barang'              => 'Plamir instan',
                'satuan_terkecil'          => 'sak',
                'satuan'                   => 'sak',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'sak',
            ],
            [
                'kode_barang'              => 'BRG-0152',
                'nama_barang'              => 'Plenybox',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
            ],
            [
                'kode_barang'              => 'BRG-0153',
                'nama_barang'              => 'Plug 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0154',
                'nama_barang'              => 'Plug 1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0155',
                'nama_barang'              => 'Plug 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0156',
                'nama_barang'              => 'Plafond',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0157',
                'nama_barang'              => 'Pakan las RD 460',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0158',
                'nama_barang'              => 'Rambuncis Brown',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0159',
                'nama_barang'              => 'Reng 0.45',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0160',
                'nama_barang'              => 'Resibon WD',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0161',
                'nama_barang'              => 'Roster',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0162',
                'nama_barang'              => 'Roster Motif',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0163',
                'nama_barang'              => 'Sambas',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
            ],
            [
                'kode_barang'              => 'BRG-0164',
                'nama_barang'              => 'SDL 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0165',
                'nama_barang'              => 'SDL 1.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0166',
                'nama_barang'              => 'SDL 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0167',
                'nama_barang'              => 'SDL 1 1/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0168',
                'nama_barang'              => 'SDD 1.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0169',
                'nama_barang'              => 'SDD 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0170',
                'nama_barang'              => 'SDD 1 1/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0171',
                'nama_barang'              => 'SDD 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0172',
                'nama_barang'              => 'SDL + SDD 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0173',
                'nama_barang'              => 'SDL 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0174',
                'nama_barang'              => 'Seal Tape Air',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0175',
                'nama_barang'              => 'Selang spiral',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
            ],
            [
                'kode_barang'              => 'BRG-0176',
                'nama_barang'              => 'Selang timbang',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
            ],
            [
                'kode_barang'              => 'BRG-0177',
                'nama_barang'              => 'Selang fleksibel BCP',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
            ],
            [
                'kode_barang'              => 'BRG-0178',
                'nama_barang'              => 'Semen All Brand',
                'satuan_terkecil'          => 'sak',
                'satuan'                   => 'sak',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'sak',
            ],
            // BRG-0179: Semen putih memiliki 2 satuan (kg & sak, 1 sak = 40 kg, default = kg)
            [
                'kode_barang'              => 'BRG-0179',
                'nama_barang'              => 'Semen putih',
                'satuan_terkecil'          => 'kg',
                'konversi'                 => [
                    [
                        'satuan'          => 'kg',
                        'jumlah_konversi' => 1,
                        'is_default'      => true,
                    ],
                    [
                        'satuan'          => 'sak',
                        'jumlah_konversi' => 40,
                        'is_default'      => false,
                    ],
                ],
            ],
            [
                'kode_barang'              => 'BRG-0180',
                'nama_barang'              => 'Serabut',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0181',
                'nama_barang'              => 'Shower bidet',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0182',
                'nama_barang'              => 'Silinder Slot',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0183',
                'nama_barang'              => 'Spigot',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0184',
                'nama_barang'              => 'Sirap',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0185',
                'nama_barang'              => 'Siku siku 3x3',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0186',
                'nama_barang'              => 'Skrub 6 x 3/8',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0187',
                'nama_barang'              => 'Skrup Fisher S8',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0188',
                'nama_barang'              => 'Skrup Gypsum',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0189',
                'nama_barang'              => 'Sok 1-3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0190',
                'nama_barang'              => 'Sok 1 1/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0191',
                'nama_barang'              => 'SOK 1.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0192',
                'nama_barang'              => 'SOK 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0193',
                'nama_barang'              => 'Sok 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0194',
                'nama_barang'              => 'Sok 2.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0195',
                'nama_barang'              => 'Sok 3',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0196',
                'nama_barang'              => 'SOK 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0197',
                'nama_barang'              => 'SOK 3/4-1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0198',
                'nama_barang'              => 'Sok 4 Dim',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0199',
                'nama_barang'              => 'Solk Talang Pvc',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0200',
                'nama_barang'              => 'Soven Timp',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0201',
                'nama_barang'              => 'Spandek 6mtr 0.20',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0202',
                'nama_barang'              => 'Spandek 7mtr 0.25',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0203',
                'nama_barang'              => 'Spandek 3 meter',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0204',
                'nama_barang'              => 'Spindel',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0205',
                'nama_barang'              => 'Stop kran 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0206',
                'nama_barang'              => 'Stop kran 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0207',
                'nama_barang'              => 'Stop kran 3',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0208',
                'nama_barang'              => 'Stop kran 3',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0209',
                'nama_barang'              => 'Stop kran 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0210',
                'nama_barang'              => 'Talang U / kotok',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0211',
                'nama_barang'              => 'Talang Karet',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0212',
                'nama_barang'              => 'Fisher s6 + skrub',
                'satuan_terkecil'          => 'dus',
                'satuan'                   => 'dus',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'dus',
            ],
            [
                'kode_barang'              => 'BRG-0213',
                'nama_barang'              => 'Te 1/2 dim',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0214',
                'nama_barang'              => 'Te 2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0215',
                'nama_barang'              => 'Te 2.5',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0216',
                'nama_barang'              => 'Te 3 dim',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0217',
                'nama_barang'              => 'Te 3 dim',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0218',
                'nama_barang'              => 'Te 3/4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0219',
                'nama_barang'              => 'Te 4 dim',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0220',
                'nama_barang'              => 'Te bidet',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0221',
                'nama_barang'              => 'Te Kuningan 1/2',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0222',
                'nama_barang'              => 'Triplek 6mm',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0223',
                'nama_barang'              => 'Triplek 9mm',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0224',
                'nama_barang'              => 'Triplek 12 mm',
                'satuan_terkecil'          => 'lembar',
                'satuan'                   => 'lembar',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lembar',
            ],
            [
                'kode_barang'              => 'BRG-0225',
                'nama_barang'              => 'Tutup Talang Pvc',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0226',
                'nama_barang'              => 'TY 4',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0227',
                'nama_barang'              => 'Tandon 200 ltr penguin',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0228',
                'nama_barang'              => 'Tandon air 1000 liter',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0229',
                'nama_barang'              => 'Tandon air 550 ltr',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0230',
                'nama_barang'              => 'Usuk 3x5x3',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0231',
                'nama_barang'              => 'Usuk 4x6x3',
                'satuan_terkecil'          => 'lonjor',
                'satuan'                   => 'lonjor',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'lonjor',
            ],
            [
                'kode_barang'              => 'BRG-0232',
                'nama_barang'              => 'WD Cleaner',
                'satuan_terkecil'          => 'tabung',
                'satuan'                   => 'tabung',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'tabung',
            ],
            [
                'kode_barang'              => 'BRG-0233',
                'nama_barang'              => 'Water Meter 1/2',
                'satuan_terkecil'          => 'set',
                'satuan'                   => 'set',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'set',
            ],
            [
                'kode_barang'              => 'BRG-0234',
                'nama_barang'              => 'Cat Stucco',
                'satuan_terkecil'          => 'galon',
                'satuan'                   => 'galon',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'galon',
            ],
            [
                'kode_barang'              => 'BRG-0235',
                'nama_barang'              => 'Obat hama bulu',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],
            [
                'kode_barang'              => 'BRG-0236',
                'nama_barang'              => 'WATERMUR 1',
                'satuan_terkecil'          => 'pcs',
                'satuan'                   => 'pcs',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'pcs',
            ],

            // BRG-0237 s/d BRG-0246 (Non-Stock / Direct)
            [
                'kode_barang'              => 'BRG-0237',
                'nama_barang'              => 'bata ringan',
                'satuan_terkecil'          => 'rit',
                'satuan'                   => 'rit',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'rit',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0238',
                'nama_barang'              => 'batu',
                'satuan_terkecil'          => 'rit',
                'satuan'                   => 'rit',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'rit',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0239',
                'nama_barang'              => 'pasir',
                'satuan_terkecil'          => 'rit',
                'satuan'                   => 'rit',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'rit',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0240',
                'nama_barang'              => 'genteng',
                'satuan_terkecil'          => 'bh',
                'satuan'                   => 'bh',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'bh',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0241',
                'nama_barang'              => 'bata merah',
                'satuan_terkecil'          => 'bh',
                'satuan'                   => 'bh',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'bh',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0242',
                'nama_barang'              => 'pasir uruk',
                'satuan_terkecil'          => 'rit',
                'satuan'                   => 'rit',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'rit',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0243',
                'nama_barang'              => 'wuwung',
                'satuan_terkecil'          => 'bh',
                'satuan'                   => 'bh',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'bh',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0244',
                'nama_barang'              => 'list gypsum',
                'satuan_terkecil'          => 'mtr',
                'satuan'                   => 'mtr',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'mtr',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0245',
                'nama_barang'              => 'cempolong',
                'satuan_terkecil'          => 'bh',
                'satuan'                   => 'bh',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'bh',
                'is_stock'                 => false,
            ],
            [
                'kode_barang'              => 'BRG-0246',
                'nama_barang'              => 'tutup cempolong',
                'satuan_terkecil'          => 'bh',
                'satuan'                   => 'bh',
                'jumlah_konversi'          => 1,
                'satuan_nota_masuk_default'=> 'bh',
                'is_stock'                 => false,
            ],
        ];

        // 2. Kumpulkan semua nama satuan unik & pastikan terdaftar di master_satuan
        $uniqueSatuanNames = [];
        foreach ($dataExcel as $row) {
            $uniqueSatuanNames[strtolower(trim($row['satuan_terkecil']))] = trim($row['satuan_terkecil']);
            if (isset($row['konversi'])) {
                foreach ($row['konversi'] as $k) {
                    $uniqueSatuanNames[strtolower(trim($k['satuan']))] = trim($k['satuan']);
                }
            } else {
                $uniqueSatuanNames[strtolower(trim($row['satuan']))] = trim($row['satuan']);
            }
        }

        // Cache Master Satuan yang sudah ada
        $existingSatuan = MasterSatuan::all();
        $masterSatuan = $existingSatuan->mapWithKeys(function ($item) {
            return [strtolower(trim($item->nama)) => $item->id];
        })->toArray();

        // Buat satuan baru yang belum ada
        foreach ($uniqueSatuanNames as $key => $rawName) {
            if (!isset($masterSatuan[$key])) {
                $created = MasterSatuan::create(['nama' => $rawName]);
                $masterSatuan[$key] = $created->id;
            }
        }

        // 3. Ambil seluruh data UBS untuk inisialisasi stock_gudang
        $allUbsIds = Ubs::pluck('id')->toArray();
        $now = now();

        DB::transaction(function () use ($dataExcel, $masterSatuan, $allUbsIds, $now) {
            // A. Batch Upsert Master Barang
            $barangUpsertData = [];
            foreach ($dataExcel as $row) {
                $satuanTerkecilKey = strtolower(trim($row['satuan_terkecil']));
                $baseUnitId = $masterSatuan[$satuanTerkecilKey] ?? null;
                $isStock = isset($row['is_stock']) ? ($row['is_stock'] ? 1 : 0) : 1;

                $barangUpsertData[] = [
                    'kode_barang'  => $row['kode_barang'],
                    'nama_barang'  => $row['nama_barang'],
                    'base_unit_id' => $baseUnitId,
                    'is_stock'     => $isStock,
                    'created_at'   => $now,
                    'updated_at'   => $now,
                ];
            }

            MasterBarang::upsert(
                $barangUpsertData,
                ['kode_barang'],
                ['nama_barang', 'base_unit_id', 'is_stock', 'updated_at']
            );

            // Ambil mapping [kode_barang => id] yang baru saja di-upsert
            $kodeBarangList = array_column($dataExcel, 'kode_barang');
            $barangMap = MasterBarang::whereIn('kode_barang', $kodeBarangList)
                ->pluck('id', 'kode_barang')
                ->toArray();

            // B. Batch Upsert Satuan Konversi
            $konversiUpsertData = [];
            foreach ($dataExcel as $row) {
                $barangId = $barangMap[$row['kode_barang']] ?? null;
                if (!$barangId) continue;

                $konversiList = $row['konversi'] ?? [
                    [
                        'satuan'          => $row['satuan'],
                        'jumlah_konversi' => $row['jumlah_konversi'] ?? 1,
                        'is_default'      => strtolower(trim($row['satuan_nota_masuk_default'] ?? $row['satuan'])) === strtolower(trim($row['satuan'])),
                    ]
                ];

                foreach ($konversiList as $k) {
                    $satuanKey = strtolower(trim($k['satuan']));
                    $satuanId = $masterSatuan[$satuanKey] ?? $masterSatuan[strtolower(trim($row['satuan_terkecil']))];

                    $konversiUpsertData[] = [
                        'barang_id'        => $barangId,
                        'satuan_id'        => $satuanId,
                        'konversi_ke_base' => $k['jumlah_konversi'],
                        'is_default'       => !empty($k['is_default']) ? 1 : 0,
                        'created_at'       => $now,
                        'updated_at'       => $now,
                    ];
                }
            }

            if (!empty($konversiUpsertData)) {
                BarangSatuanKonversi::upsert(
                    $konversiUpsertData,
                    ['barang_id', 'satuan_id'],
                    ['konversi_ke_base', 'is_default', 'updated_at']
                );
            }

            // C. Batch Upsert Stock Gudang UBS (Hanya untuk barang dengan is_stock = true)
            if (!empty($allUbsIds)) {
                // Filter kode barang yang is_stock = true
                $stockableKodeList = [];
                foreach ($dataExcel as $row) {
                    $isStock = $row['is_stock'] ?? true;
                    if ($isStock) {
                        $stockableKodeList[] = $row['kode_barang'];
                    }
                }

                $stockGudangUpsertData = [];
                foreach ($barangMap as $kode => $barangId) {
                    if (!in_array($kode, $stockableKodeList)) {
                        continue;
                    }

                    foreach ($allUbsIds as $ubsId) {
                        $stockGudangUpsertData[] = [
                            'barang_id'     => $barangId,
                            'stock_type'    => 'UBS',
                            'ubs_id'        => $ubsId,
                            'jumlah_stock'  => 0,
                            'minimal_stock' => 0,
                            'created_at'    => $now,
                            'updated_at'    => $now,
                        ];
                    }
                }

                // Chunk per 500 rows agar query sangat cepat dan tidak melebihi parameter limit
                foreach (array_chunk($stockGudangUpsertData, 500) as $chunk) {
                    StockGudang::upsert(
                        $chunk,
                        ['barang_id', 'stock_type', 'ubs_id'],
                        ['updated_at']
                    );
                }
            }
        });

        $this->command->info('Seeder Master Barang & Satuan Konversi (246 item) berhasil dijalankan secara instan!');
    }
}
